# Generated by Django 4.2.6 on 2023-10-17 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255)),
                ('subject_score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syndey_participant', models.IntegerField()),
                ('syndey_percentile', models.IntegerField()),
                ('correct_answer_percentage_per_class', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category_id', models.IntegerField()),
                ('year_level_name', models.CharField(max_length=255)),
                ('assessment_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_app.assessmentarea')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_app.awards')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_app.class')),
                ('correct_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_app.answers')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_app.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_app.subject')),
            ],
        ),
    ]
