# Generated by Django 4.2.6 on 2023-10-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0002_alter_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentarea',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='awards',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='fullname',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
